terraform {
  required_version = ">= 1.3.0"
}

# Generate a .env file for docker compose
resource "local_file" "compose_env" {
  filename = "${path.root}/.env"

  content  = <<EOT
# Generated by Terraform
POSTGRES_USER=${var.pg_user}
POSTGRES_PASSWORD=${var.pg_password}
POSTGRES_DB=${var.pg_db}
DATABASE_URL=postgresql+psycopg://${var.pg_user}:${var.pg_password}@localhost:5432/${var.pg_db}
CORS_ORIGIN=${var.cors_origin}
JWT_SECRET=${var.jwt_secret}
EOT
}
